driver: oracle.jdbc.driver.OracleDriver
url: jdbc:oracle:thin:@oracle-xe:1521:XE
username: admin
password: Oracle123!
changeLogFile: changelog/master.xml
liquibaseSchemaName: LIQUIBASE
liquibaseCatalogName:
outputFile: /tmp/update.sql
classpath: /opt/liquibase/lib/ojdbc11.jar:/opt/liquibase/lib/liquibase-oracle.jar
